### ISSUE TITLE
建议完善路径目录名的判断

### ISSUE THREAD

**Issue by dyfgkxue** [adavak/Win_ISO_Patching_Scripts_zhCN#10]
你提供的 Win_ISO_Patching_Scripts_zhCN 补丁集成工具很好用，非常感谢！
有个小问题，希望完善一下对上一级路径目录名的判断：
该工具会在工具所在目录的上一级目录创建临时目录，并进行一些操作，恰巧我的上一级目录名中使用了&符号，上一级目录名为：D:\OS_ISO_Patching_Win10&11，运行该工具过程中出现两次错误提示：'D:\OS_ISO_Patching_Win10' 不是内部或外部命令，也不是可运行的程序或批处理文件。系统找不到指定的路径。这应该是&符号造成的，建议对上一级目录名进行一下判断。
注：使用 2023.5d_3rd 版（未修改script_22621_x64.txt）时发现此问题。

**Comment by adavak** [comment]
![图片](https://github.com/adavak/Win_ISO_Patching_Scripts_zhCN/assets/32241/79c09ae4-419e-4f87-80ae-ef824ef3967b)

解决方法，别用 “&”，那是 Windows 特殊字符。
