### ISSUE TITLE
重新打包的镜像日期怎样都修改为打包的日期的？

### ISSUE THREAD

**Issue by uranus829** [adavak/Win_ISO_Patching_Scripts_zhCN#11]
发现A大打包的镜像日期都是打包的日期，但是脚本打包的日期为什么不是所有都是打包的日期的？请问A大是怎么操作的？谢谢

**Comment by adavak** [comment]
我自己生成的调用了 cdimage 的日期格式，抓取了当前的日期然后生成的。

详情请见：
https://learn.microsoft.com/zh-cn/windows-hardware/manufacture/desktop/oscdimg-command-line-options?view=windows-11

关键词 ·-t·
