### ISSUE TITLE
脚本支持server 2019吗？

### ISSUE THREAD

**Issue by uranus829** [adavak/Win_ISO_Patching_Scripts_zhCN#2]
A大，镜像我放了SW_DVD9_Win_Server_STD_CORE_2019_64Bit_ChnSimp_DC_STD_MLF_X21-96577.iso，运行start.cmd看到下载的是win10的msu？可以支持server 2019的msu下载吗？

![image](https://user-images.githubusercontent.com/46716344/141662238-2b039fe6-e7a8-432d-ab1b-c6a7fd113051.png)

**Comment by adavak** [comment]
支持。
