### ISSUE TITLE
求个交流群

### ISSUE THREAD

**Issue by wpf973** [adavak/Win_ISO_Patching_Scripts_zhCN#3]
求个交流群

**Comment by adavak** [comment]
没有交流群，有啥问题这里提。

**Comment by wpf973** [comment]
17763.2330.211117-1259 都代表什么

**Comment by adavak** [comment]
17763是版本，也就是1809
2330是修正补丁编号，每次打补丁都会变化
211117-1259是补丁编译日期。这个没啥用。
