### ISSUE TITLE
支持其他语言版本集成更新吗？

### ISSUE THREAD

**Issue by iwowcn** [adavak/Win_ISO_Patching_Scripts_zhCN#7]
脚本支持其他语言，比如英文版、日文版集成更新吗？

**Comment by adavak** [comment]
支持，其实就是 .net 语系包有区别，可以改下脚本。

**Comment by adavak** [comment]
你要打补丁的版本是哪个？

**Comment by iwowcn** [comment]
> 你要打补丁的版本是哪个？

Windows10  2021  LTSC 日文版

**Comment by adavak** [comment]
这里对于 ltsc 2021 的 .net 语言包指的是4.8.1版本的，也就是我放到 bin 之内的那一个。kb5011050。

由于微软没讲此语言包上网，所以没有链接可以直接下载 cab 格式的文件，需要从 4.8.1 的页面下载 exe 格式的离线包之后解压。

你要的在 ndp481-x86-x64-allos-jpn.exe 内。
