### ISSUE TITLE
ltsb_x86 异常

### ISSUE THREAD

**Issue by wpf973** [adavak/Win_ISO_Patching_Scripts_zhCN#8]
cn_windows_10_enterprise_2016_ltsb_x86_dvd_9057089
![image](https://user-images.githubusercontent.com/22835238/204831805-58f1b958-97a1-4cbe-b542-c1ba7ebfb6b8.png)

**Comment by wpf973** [comment]
自己改的报错了！大佬修复一下

**Comment by adavak** [comment]
因为官方 1607 19393 x86 的映像有毛病，不能离线打补丁，需要修复一下才能用，所以脚本就把那个版本屏蔽掉了。
你改好了也不能用的。

具体请去 MDL 论坛查看。
https://forums.mydigitallife.net/posts/1459586/
